# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class JiraBranch < Formula
  desc "Create a jira branch for a ticket"
  homepage "https://github.com/manuphatak/jira-branch"
  version "0.2.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/manuphatak/jira-branch/releases/download/v0.2.5/jira-branch_0.2.5_Darwin_arm64.tar.gz"
      sha256 "44cadcb32a44fbe440f90845299ed31f6f1a724295cf7d168bfb0af277ca4b8e"

      def install
        bin.install "jira-branch"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/manuphatak/jira-branch/releases/download/v0.2.5/jira-branch_0.2.5_Darwin_x86_64.tar.gz"
      sha256 "b440ef703c367f1f46c9b146384474ce4825eeb0bc23faf8b22fa9ad431da334"

      def install
        bin.install "jira-branch"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/manuphatak/jira-branch/releases/download/v0.2.5/jira-branch_0.2.5_Linux_x86_64.tar.gz"
      sha256 "bbd14524cf5f364fefe006e1282adbbed778e0edbc826ef01cd8be7a79284893"

      def install
        bin.install "jira-branch"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/manuphatak/jira-branch/releases/download/v0.2.5/jira-branch_0.2.5_Linux_arm64.tar.gz"
      sha256 "cf659603b70b1d9e241a176c8afb6c0a3580ea994b9f84c2a5dd7bc137c7cd02"

      def install
        bin.install "jira-branch"
      end
    end
  end
end
