# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class JiraBranch < Formula
  desc "Create a jira branch for a ticket"
  homepage "https://github.com/manuphatak/jira-branch"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/manuphatak/jira-branch/releases/download/v1.0.0/jira-branch_1.0.0_Darwin_x86_64.tar.gz"
      sha256 "84e635542a165e3d458c56bc02b7d375c9de131980cd4e79cfdeb0a4189545ad"

      def install
        bin.install "jira-branch"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/manuphatak/jira-branch/releases/download/v1.0.0/jira-branch_1.0.0_Darwin_arm64.tar.gz"
      sha256 "94ce07b2510a1afb39b6a74d7eab9fd7c0b814bd43162660ef1a0fc7be5eb731"

      def install
        bin.install "jira-branch"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/manuphatak/jira-branch/releases/download/v1.0.0/jira-branch_1.0.0_Linux_arm64.tar.gz"
      sha256 "51a16d69c4ae18cc8f6f370c6a18870ba70f5a96494b68ced460aad672373fc5"

      def install
        bin.install "jira-branch"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/manuphatak/jira-branch/releases/download/v1.0.0/jira-branch_1.0.0_Linux_x86_64.tar.gz"
      sha256 "08bff26db3dc81d6e0dbfa2f4769e1e47547e2f0ecb053d8d9014d5e5e7546b1"

      def install
        bin.install "jira-branch"
      end
    end
  end
end
